version: 2
updates:
- package-ecosystem: npm
  directory: "/bot"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 0
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
